services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: devdocs_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: devdocs
      POSTGRES_PASSWORD: devdocs
      POSTGRES_DB: devdocs_ai
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: